name: test

on:
  - push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
    # - uses: treosh/lighthouse-ci-action@v2
    #   with:
    #     configPath: .lighthouserc.json
      - uses: docker://catsoss/node-headless-chrome:latest
        with:
          args: 'npx -p @lhci/cli -c "lhci autorun"'
      - uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: .lighthouseci
